[package]
name = "non-polymorphic "
version = "0.1.0"
authors = ["Kazuki Yoshida <idkphys.030zzz@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.10"

[[bin]]
name = "non-polymorphic"
path = "src/non_polymorphic.rs"

[[bin]]
name = "polymorphic"
path = "src/polymorphic.rs"
